def display_case_study():
    print("===========================================")
    print("DECODELABS PHISHING AWARENESS ANALYSIS DASHBOARD(PROJECT 3)")
    print("=============================================")
    print("\n---Simulated Suspicious Email Data---")
    print("From: HR Department <hr-update@decode1abs-portal.com></hr-update>")
    print("To: employee@decodelabs.tech")
    print("subject: URGENT: Complete 2026 Healthcare Benefits Questionaire in 24 Hours!")
    print("\nMessage Body:")
    print("Dear Team,")
    print("Please click the link below immediately to verify your personal records.")
    print("Failure to respond will result in a Suspicious of your healthcare coverage.")
    print("Link: http://www.decodelabs.tech.login-update.com/verification")
    print("============================================================\n")
def analyze_phishing():
     display_case_study()
     print("Let's analyze this message step-by-step to identify potential red flags.\n")
     # interactive red Flag walkthrough
     input("Press Enter to extract Red Flag #1(sender Domain)...")
     print("\n RED FLAG 1: Dispay Name Spoofing & Lookalike Domain") 
     print("  -The sender email uses'decode1abs-portal.com' (with a number '1') instead of 'decodelabs.tech'. ")

     print("-" * 50)
     input("Press enter to extract Red Flag #2( Suspicious URL Structure)...")
     print("\n RED FLAG 2:Subdomain Manipulation")
     print("  -The link reads 'www.decodelabs.tech.login-update.com'.")
     print("  -The actual root domain is 'login-update.com'.'decodelabs.tech' is just a fake Subdomain prefix!")

     print("-" *50)
     input("Press enter to extract Red Flag #3(congitive psychology Triggers)...")
     print("\n RED FLAG 3:Artificial urgency & fear Tactics")
     print("  -The  subject uses 'URGENT' and a '24 Hours' deadline to pressure you into bypassing logic.")
     print("It uses fear by threatening a 'suspension' of your healthcare coverage'.")

     print("=" *69)
     print("FINAL ASSESSMENT SUMMARY")
     print("=" *69)
     print(" STATUS: MALICIOUS( phishing Attempt)")
     print("WHY IT IS UNSAFE:")
     print("The email manipulates trust through authority impersonation and creates high anxiety.")
     print(" The link point to a credential harvesting credential domain designed to steal data.")
     print("\n ACTIONABLE OUTCOME: [BLOCK DOMAIN & ESCALATE TO SOC]")
     print("============================================================================================")
if __name__ =="__main__":
    analyze_phishing()